[versions]
kotlinx-coroutines = "1.10.2"
apksig = "8.12.3"
bcpkix = "1.83"
kotlinx-serialization = "1.9.0"

[libraries]
android-tools-build = { group = "com.android.tools.build", name = "apksig", version.ref = "apksig" }
bouncycastle-pkix = { group = "org.bouncycastle", name = "bcpkix-jdk18on", version.ref = "bcpkix" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
