// SPDX-License-Identifier: GPL-3.0-only
//
// Message values and spellings are pinned to official Meta/Oculus SDK releases:
// - com.meta.xr.sdk.platform 205.0.0 (tarball SHA-1
//   5953e5d03c05643223b11317969db436dd1719c1), published by Meta's UPM registry;
// - Oculus Platform SDK 85.0 for the native C identifier spellings;
// - Oculus Platform SDK 40.0 (2022) and 1.43.0 for retired legacy messages.
// The latter three use their generated Include/OVR_MessageType.h files.
//
// The exact string convention and fallback were checked against the Authenticode-valid
// Oculus VR, LLC LibOVRPlatform64_1.dll 1.42.0.0 (MD5
// 47535577f8fa064f7aa48d4e40945f7c): known values return their complete
// ovrMessage_* identifier; zero and unrecognized values return "UNKNOWN".
// See licenses/OCULUS-PLATFORM-SDK.txt for the SDK notice.

#include <cstdint>

extern "C" __attribute__((visibility("default"))) const char*
ovrMessageType_ToString(std::uint32_t value) noexcept {
    switch (value) {
        case 0u:
            return "UNKNOWN";
        case 0x03E76231u:
            return "ovrMessage_Achievements_AddCount";
        case 0x14AA2129u:
            return "ovrMessage_Achievements_AddFields";
        case 0x03D3458Du:
            return "ovrMessage_Achievements_GetAllDefinitions";
        case 0x4F9FDE1Du:
            return "ovrMessage_Achievements_GetAllProgress";
        case 0x629101BCu:
            return "ovrMessage_Achievements_GetDefinitionsByName";
        case 0x2A7DD255u:
            return "ovrMessage_Achievements_GetNextAchievementDefinitionArrayPage";
        case 0x2F42E727u:
            return "ovrMessage_Achievements_GetNextAchievementProgressArrayPage";
        case 0x152663B1u:
            return "ovrMessage_Achievements_GetProgressByName";
        case 0x593CCBDDu:
            return "ovrMessage_Achievements_Unlock";
        case 0x04E5CF62u:
            return "ovrMessage_ApplicationLifecycle_GetRegisteredPIDs";
        case 0x3AAF591Du:
            return "ovrMessage_ApplicationLifecycle_GetSessionKey";
        case 0x4DB6AFF8u:
            return "ovrMessage_ApplicationLifecycle_RegisterSessionKey";
        case 0x68670A0Eu:
            return "ovrMessage_Application_GetVersion";
        case 0x54E2D1F8u:
            return "ovrMessage_Application_LaunchOtherApp";
        case 0x6D5D7886u:
            return "ovrMessage_AssetFile_Delete";
        case 0x5AE8CD52u:
            return "ovrMessage_AssetFile_DeleteById";
        case 0x420AC1CFu:
            return "ovrMessage_AssetFile_DeleteByName";
        case 0x11449FC5u:
            return "ovrMessage_AssetFile_Download";
        case 0x2D008992u:
            return "ovrMessage_AssetFile_DownloadById";
        case 0x6336CEFAu:
            return "ovrMessage_AssetFile_DownloadByName";
        case 0x080AD3C7u:
            return "ovrMessage_AssetFile_DownloadCancel";
        case 0x51659514u:
            return "ovrMessage_AssetFile_DownloadCancelById";
        case 0x446AECFAu:
            return "ovrMessage_AssetFile_DownloadCancelByName";
        case 0x4AFC6F74u:
            return "ovrMessage_AssetFile_GetList";
        case 0x02D32F60u:
            return "ovrMessage_AssetFile_Status";
        case 0x5D955D38u:
            return "ovrMessage_AssetFile_StatusById";
        case 0x41CFDA50u:
            return "ovrMessage_AssetFile_StatusByName";
        case 0x76A42EEEu:
            return "ovrMessage_CloudStorage2_GetUserDirectoryPath";
        case 0x28DA456Du:
            return "ovrMessage_CloudStorage_Delete";
        case 0x5C07A2EFu:
            return "ovrMessage_CloudStorage_GetNextCloudStorageMetadataArrayPage";
        case 0x40846B41u:
            return "ovrMessage_CloudStorage_Load";
        case 0x7327A50Du:
            return "ovrMessage_CloudStorage_LoadBucketMetadata";
        case 0x445A52F2u:
            return "ovrMessage_CloudStorage_LoadConflictMetadata";
        case 0x326ADA36u:
            return "ovrMessage_CloudStorage_LoadHandle";
        case 0x03E6A292u:
            return "ovrMessage_CloudStorage_LoadMetadata";
        case 0x30588D05u:
            return "ovrMessage_CloudStorage_ResolveKeepLocal";
        case 0x7525A306u:
            return "ovrMessage_CloudStorage_ResolveKeepRemote";
        case 0x4BBB5C2Eu:
            return "ovrMessage_CloudStorage_Save";
        case 0x186B58B1u:
            return "ovrMessage_Entitlement_GetIsViewerEntitled";
        case 0x1FBB72D9u:
            return "ovrMessage_IAP_ConsumePurchase";
        case 0x1BD94AAFu:
            return "ovrMessage_IAP_GetNextProductArrayPage";
        case 0x47570A95u:
            return "ovrMessage_IAP_GetNextPurchaseArrayPage";
        case 0x7E9ACAF5u:
            return "ovrMessage_IAP_GetProductsBySKU";
        case 0x3A0F8419u:
            return "ovrMessage_IAP_GetViewerPurchases";
        case 0x63599E2Bu:
            return "ovrMessage_IAP_GetViewerPurchasesDurableCache";
        case 0x3F9B0D0Du:
            return "ovrMessage_IAP_LaunchCheckoutFlow";
        case 0x1F90F0D5u:
            return "ovrMessage_LanguagePack_GetCurrent";
        case 0x5B4FBBE0u:
            return "ovrMessage_LanguagePack_SetCurrent";
        case 0x5DB3474Cu:
            return "ovrMessage_Leaderboard_GetEntries";
        case 0x18378BEFu:
            return "ovrMessage_Leaderboard_GetEntriesAfterRank";
        case 0x4E207CD9u:
            return "ovrMessage_Leaderboard_GetNextEntries";
        case 0x4901DAC0u:
            return "ovrMessage_Leaderboard_GetPreviousEntries";
        case 0x117FC8FEu:
            return "ovrMessage_Leaderboard_WriteEntry";
        case 0x489A6995u:
            return "ovrMessage_Livestreaming_GetStatus";
        case 0x369C7683u:
            return "ovrMessage_Livestreaming_PauseStream";
        case 0x22526D8Fu:
            return "ovrMessage_Livestreaming_ResumeStream";
        case 0x1E6532C8u:
            return "ovrMessage_Matchmaking_Browse";
        case 0x66429E5Bu:
            return "ovrMessage_Matchmaking_Browse2";
        case 0x206849AFu:
            return "ovrMessage_Matchmaking_Cancel";
        case 0x10FE8DD4u:
            return "ovrMessage_Matchmaking_Cancel2";
        case 0x604C5DC8u:
            return "ovrMessage_Matchmaking_CreateAndEnqueueRoom";
        case 0x295BEADBu:
            return "ovrMessage_Matchmaking_CreateAndEnqueueRoom2";
        case 0x033B132Au:
            return "ovrMessage_Matchmaking_CreateRoom";
        case 0x496DA384u:
            return "ovrMessage_Matchmaking_CreateRoom2";
        case 0x40C16C71u:
            return "ovrMessage_Matchmaking_Enqueue";
        case 0x121212B5u:
            return "ovrMessage_Matchmaking_Enqueue2";
        case 0x708A4064u:
            return "ovrMessage_Matchmaking_EnqueueRoom";
        case 0x5528DBA4u:
            return "ovrMessage_Matchmaking_EnqueueRoom2";
        case 0x3C215F94u:
            return "ovrMessage_Matchmaking_GetAdminSnapshot";
        case 0x42FC9438u:
            return "ovrMessage_Matchmaking_GetStats";
        case 0x4D32D7FDu:
            return "ovrMessage_Matchmaking_JoinRoom";
        case 0x1A36D18Du:
            return "ovrMessage_Matchmaking_ReportResultInsecure";
        case 0x44D40945u:
            return "ovrMessage_Matchmaking_StartMatch";
        case 0x00E38AEFu:
            return "ovrMessage_Media_ShareToFacebook";
        case 0x0621FB77u:
            return "ovrMessage_Notification_GetNextRoomInviteNotificationArrayPage";
        case 0x6F916B92u:
            return "ovrMessage_Notification_GetRoomInvites";
        case 0x717259E3u:
            return "ovrMessage_Notification_MarkAsRead";
        case 0x47933760u:
            return "ovrMessage_Party_GetCurrent";
        case 0x57B752B3u:
            return "ovrMessage_RichPresence_Clear";
        case 0x586F2D14u:
            return "ovrMessage_RichPresence_GetDestinations";
        case 0x67367F45u:
            return "ovrMessage_RichPresence_GetNextDestinationArrayPage";
        case 0x3C147509u:
            return "ovrMessage_RichPresence_Set";
        case 0x75D6E377u:
            return "ovrMessage_Room_CreateAndJoinPrivate";
        case 0x5A3A6243u:
            return "ovrMessage_Room_CreateAndJoinPrivate2";
        case 0x659A8FB8u:
            return "ovrMessage_Room_Get";
        case 0x09A6A504u:
            return "ovrMessage_Room_GetCurrent";
        case 0x0E0017E5u:
            return "ovrMessage_Room_GetCurrentForUser";
        case 0x1E325792u:
            return "ovrMessage_Room_GetInvitableUsers";
        case 0x4F53E8B0u:
            return "ovrMessage_Room_GetInvitableUsers2";
        case 0x0983FD77u:
            return "ovrMessage_Room_GetModeratedRooms";
        case 0x4E8379C6u:
            return "ovrMessage_Room_GetNextRoomArrayPage";
        case 0x4129EC13u:
            return "ovrMessage_Room_InviteUser";
        case 0x16CA8F09u:
            return "ovrMessage_Room_Join";
        case 0x4DAB1C42u:
            return "ovrMessage_Room_Join2";
        case 0x49835736u:
            return "ovrMessage_Room_KickUser";
        case 0x323FE273u:
            return "ovrMessage_Room_LaunchInvitableUserFlow";
        case 0x72382475u:
            return "ovrMessage_Room_Leave";
        case 0x3044852Fu:
            return "ovrMessage_Room_SetDescription";
        case 0x026E4028u:
            return "ovrMessage_Room_UpdateDataStore";
        case 0x370BB7ACu:
            return "ovrMessage_Room_UpdateMembershipLockStatus";
        case 0x32B63D1Du:
            return "ovrMessage_Room_UpdateOwner";
        case 0x1141029Bu:
            return "ovrMessage_Room_UpdatePrivateRoomJoinPolicy";
        case 0x6BCF9E47u:
            return "ovrMessage_User_Get";
        case 0x06A85ABEu:
            return "ovrMessage_User_GetAccessToken";
        case 0x436F345Du:
            return "ovrMessage_User_GetLoggedInUser";
        case 0x587C2A8Du:
            return "ovrMessage_User_GetLoggedInUserFriends";
        case 0x5E870B87u:
            return "ovrMessage_User_GetLoggedInUserFriendsAndRooms";
        case 0x295FBA30u:
            return "ovrMessage_User_GetLoggedInUserRecentlyMetUsersAndRooms";
        case 0x7FBDD2DFu:
            return "ovrMessage_User_GetNextUserAndRoomArrayPage";
        case 0x267CF743u:
            return "ovrMessage_User_GetNextUserArrayPage";
        case 0x18F0B01Bu:
            return "ovrMessage_User_GetOrgScopedID";
        case 0x67526A83u:
            return "ovrMessage_User_GetSdkAccounts";
        case 0x22810483u:
            return "ovrMessage_User_GetUserProof";
        case 0x0904B598u:
            return "ovrMessage_User_LaunchFriendRequestFlow";
        case 0x0A397297u:
            return "ovrMessage_User_LaunchProfile";
        case 0x453FC9AAu:
            return "ovrMessage_Voip_SetSystemVoipSuppressed";
        case 0x04B34CA3u:
            return "ovrMessage_Notification_ApplicationLifecycle_LaunchIntentChanged";
        case 0x2FDD0CCDu:
            return "ovrMessage_Notification_AssetFile_DownloadUpdate";
        case 0x750C5099u:
            return "ovrMessage_Notification_Cal_FinalizeApplication";
        case 0x2E7451F5u:
            return "ovrMessage_Notification_Cal_ProposeApplication";
        case 0x7DD46E2Fu:
            return "ovrMessage_Notification_HTTP_Transfer";
        case 0x2247596Eu:
            return "ovrMessage_Notification_Livestreaming_StatusChange";
        case 0x0BC3FCD7u:
            return "ovrMessage_Notification_Matchmaking_MatchFound";
        case 0x5E02D49Au:
            return "ovrMessage_Notification_Networking_ConnectionStateChange";
        case 0x4D31E2CFu:
            return "ovrMessage_Notification_Networking_PeerConnectRequest";
        case 0x51153012u:
            return "ovrMessage_Notification_Networking_PingResult";
        case 0x1D118AB2u:
            return "ovrMessage_Notification_Party_PartyUpdate";
        case 0x6D1071B1u:
            return "ovrMessage_Notification_Room_InviteAccepted";
        case 0x6A499D54u:
            return "ovrMessage_Notification_Room_InviteReceived";
        case 0x60EC3C2Fu:
            return "ovrMessage_Notification_Room_RoomUpdate";
        case 0x36243816u:
            return "ovrMessage_Notification_Voip_ConnectRequest";
        case 0x34EFA660u:
            return "ovrMessage_Notification_Voip_StateChange";
        case 0x58D254A5u:
            return "ovrMessage_Notification_Voip_SystemVoipState";
        case 0x35692F2Bu:
            return "ovrMessage_PlatformInitializeWithAccessToken";
        case 0x51F8CE0Cu:
            return "ovrMessage_Platform_InitializeStandaloneOculus";
        case 0x1AD307B4u:
            return "ovrMessage_PlatformInitializeAndroidAsynchronous";
        case 0x6DA7BA8Fu:
            return "ovrMessage_PlatformInitializeWindowsAsynchronous";
        case 0x6859D641u:
            return "ovrMessage_Challenges_Create";
        case 0x568E76C0u:
            return "ovrMessage_Challenges_DeclineInvite";
        case 0x264885CAu:
            return "ovrMessage_Challenges_Delete";
        case 0x77584EF3u:
            return "ovrMessage_Challenges_Get";
        case 0x121AB45Fu:
            return "ovrMessage_Challenges_GetEntries";
        case 0x08891A7Fu:
            return "ovrMessage_Challenges_GetEntriesAfterRank";
        case 0x316509DCu:
            return "ovrMessage_Challenges_GetEntriesByIds";
        case 0x43264356u:
            return "ovrMessage_Challenges_GetList";
        case 0x5B7CA1B6u:
            return "ovrMessage_Challenges_GetNextChallenges";
        case 0x7F4CA0C6u:
            return "ovrMessage_Challenges_GetNextEntries";
        case 0x0EB4040Du:
            return "ovrMessage_Challenges_GetPreviousChallenges";
        case 0x78C90470u:
            return "ovrMessage_Challenges_GetPreviousEntries";
        case 0x21248069u:
            return "ovrMessage_Challenges_Join";
        case 0x296116E5u:
            return "ovrMessage_Challenges_Leave";
        case 0x1175BE60u:
            return "ovrMessage_Challenges_UpdateInfo";
        case 0x6DAA9CC3u:
            return "ovrMessage_GroupPresence_Clear";
        case 0x234BC3F1u:
            return "ovrMessage_GroupPresence_GetInvitableUsers";
        case 0x04F8C0F2u:
            return "ovrMessage_GroupPresence_GetNextApplicationInviteArrayPage";
        case 0x08260AB1u:
            return "ovrMessage_GroupPresence_GetSentInvites";
        case 0x0F9ECF9Fu:
            return "ovrMessage_GroupPresence_LaunchInvitePanel";
        case 0x2955AF24u:
            return "ovrMessage_GroupPresence_LaunchMultiplayerErrorDialog";
        case 0x1577036Fu:
            return "ovrMessage_GroupPresence_LaunchRejoinDialog";
        case 0x35728882u:
            return "ovrMessage_GroupPresence_LaunchRosterPanel";
        case 0x0DCBD364u:
            return "ovrMessage_GroupPresence_SendInvites";
        case 0x675F5C24u:
            return "ovrMessage_GroupPresence_Set";
        case 0x4C5B268Au:
            return "ovrMessage_GroupPresence_SetDestination";
        case 0x2A8F1055u:
            return "ovrMessage_GroupPresence_SetIsJoinable";
        case 0x48FF55BEu:
            return "ovrMessage_GroupPresence_SetLobbySession";
        case 0x314C84B8u:
            return "ovrMessage_GroupPresence_SetMatchSession";
        case 0x6AD44EF8u:
            return "ovrMessage_Leaderboard_Get";
        case 0x39607BFCu:
            return "ovrMessage_Leaderboard_GetEntriesByIds";
        case 0x35F6769Bu:
            return "ovrMessage_Leaderboard_GetNextLeaderboardArrayPage";
        case 0x72C692FAu:
            return "ovrMessage_Leaderboard_WriteEntryWithSupplementaryMetric";
        case 0x5C896F3Eu:
            return "ovrMessage_UserDataStore_PrivateDeleteEntryByKey";
        case 0x6C8A8228u:
            return "ovrMessage_UserDataStore_PrivateGetEntries";
        case 0x1C068319u:
            return "ovrMessage_UserDataStore_PrivateGetEntryByKey";
        case 0x41D2828Bu:
            return "ovrMessage_UserDataStore_PrivateWriteEntry";
        case 0x1DD5E5FBu:
            return "ovrMessage_UserDataStore_PublicDeleteEntryByKey";
        case 0x167D4BC2u:
            return "ovrMessage_UserDataStore_PublicGetEntries";
        case 0x195C66C6u:
            return "ovrMessage_UserDataStore_PublicGetEntryByKey";
        case 0x34364A0Au:
            return "ovrMessage_UserDataStore_PublicWriteEntry";
        case 0x7D201556u:
            return "ovrMessage_User_GetBlockedUsers";
        case 0x7C2AFDCBu:
            return "ovrMessage_User_GetNextBlockedUserArrayPage";
        case 0x2309F399u:
            return "ovrMessage_User_GetNextUserCapabilityArrayPage";
        case 0x6FD62528u:
            return "ovrMessage_User_LaunchBlockFlow";
        case 0x14A22A97u:
            return "ovrMessage_User_LaunchUnblockFlow";
        case 0x744CE345u:
            return "ovrMessage_Voip_GetMicrophoneAvailability";
        case 0x679A84B6u:
            return "ovrMessage_Notification_GroupPresence_InvitationsSent";
        case 0x773889F6u:
            return "ovrMessage_Notification_GroupPresence_JoinIntentReceived";
        case 0x4737EA1Du:
            return "ovrMessage_Notification_GroupPresence_LeaveIntentReceived";
        case 0x073484CAu:
            return "ovrMessage_Notification_NetSync_ConnectionStatusChanged";
        case 0x387E7F36u:
            return "ovrMessage_Notification_NetSync_SessionsChanged";
        case 0x07F9C880u:
            return "ovrMessage_Notification_Session_InvitationsSent";
        case 0x3E20CB57u:
            return "ovrMessage_Notification_Voip_MicrophoneAvailabilityStateUpdate";
        case 0x6EE4F33Cu:
            return "ovrMessage_Notification_Vrcamera_GetDataChannelMessageUpdate";
        case 0x37F21084u:
            return "ovrMessage_Notification_Vrcamera_GetSurfaceUpdate";
        case 0x4B8EFC86u:
            return "ovrMessage_AbuseReport_ReportRequestHandled";
        case 0x7C2060DEu:
            return "ovrMessage_Application_CancelAppDownload";
        case 0x5534A924u:
            return "ovrMessage_Application_CheckAppDownloadProgress";
        case 0x14806B85u:
            return "ovrMessage_Application_InstallAppUpdateAndRelaunch";
        case 0x44FC006Eu:
            return "ovrMessage_Application_StartAppDownload";
        case 0x05F1E153u:
            return "ovrMessage_Avatar_LaunchAvatarEditor";
        case 0x3271ABDAu:
            return "ovrMessage_DeviceApplicationIntegrity_GetIntegrityToken";
        case 0x521ADF0Du:
            return "ovrMessage_GroupPresence_SetDeeplinkMessageOverride";
        case 0x663A8B5Fu:
            return "ovrMessage_PushNotification_Register";
        case 0x21CBE0C0u:
            return "ovrMessage_UserAgeCategory_Get";
        case 0x2E4DD8D6u:
            return "ovrMessage_UserAgeCategory_Report";
        case 0x5793F456u:
            return "ovrMessage_User_GetLinkedAccounts";
        case 0x70BA3AEEu:
            return "ovrMessage_User_GetLoggedInUserManagedInfo";
        case 0x24472F6Cu:
            return "ovrMessage_Notification_AbuseReport_ReportButtonPressed";
        default:
            return "UNKNOWN";
    }
}
